// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jntijvmrvghuvhknksnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudGlqdm1ydmdodXZoa25rc252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzOTgyOTQsImV4cCI6MjA4Mzk3NDI5NH0.YDZTBhM-7D3h6yVj-zgXWMpZX_OfCf33oczXOtiWLN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});